# Contract deployment mapping
contracts:
  core:
    script: "DeployCore"
    contracts:
      OtimDelegate:
        expected_addr_envvar: "EXPECTED_OTIM_DELEGATE_ADDRESS"
      Gateway:
        expected_addr_envvar: "EXPECTED_GATEWAY_ADDRESS"
      InstructionStorage:
        expected_addr_envvar: "EXPECTED_INSTRUCTION_STORAGE_ADDRESS"
      ActionManager:
        expected_addr_envvar: "ACTION_MANAGER_ADDRESS"

  infrastructure:
    contracts:
      FeeTokenRegistry:
        expected_addr_envvar: "EXPECTED_FEE_TOKEN_REGISTRY_ADDRESS"
      Treasury:
        expected_addr_envvar: "EXPECTED_TREASURY_ADDRESS"

  actions:
    contracts:
      TransferAction:
        expected_addr_envvar: "EXPECTED_TRANSFER_ACTION_ADDRESS"
      TransferERC20Action:
        expected_addr_envvar: "EXPECTED_TRANSFER_ERC20_ACTION_ADDRESS"
      RefuelAction:
        expected_addr_envvar: "EXPECTED_REFUEL_ACTION_ADDRESS"
      RefuelERC20Action:
        expected_addr_envvar: "EXPECTED_REFUEL_ERC20_ACTION_ADDRESS"
      DeactivateInstructionAction:
        expected_addr_envvar: "EXPECTED_DEACTIVATE_INSTRUCTION_ACTION_ADDRESS"
      UniswapV3ExactInputAction:
      TransferCCTPAction:
      SweepCCTPAction:
