# Contract deployment mapping
contracts:
  core:
    script: "DeployCore"
    contracts:
      OtimDelegate:
        expected_addr_envvar: "EXPECTED_OTIM_DELEGATE_ADDRESS"
        chain_config_key: "otim_delegate_addr"
      Gateway:
        expected_addr_envvar: "EXPECTED_GATEWAY_ADDRESS"
        chain_config_key: "gateway_addr"
      InstructionStorage:
        expected_addr_envvar: "EXPECTED_INSTRUCTION_STORAGE_ADDRESS"
        chain_config_key: "instruction_storage_addr"
      ActionManager:
        expected_addr_envvar: "ACTION_MANAGER_ADDRESS"
        chain_config_key: "action_manager_addr"

  infrastructure:
    contracts:
      FeeTokenRegistry:
        expected_addr_envvar: "EXPECTED_FEE_TOKEN_REGISTRY_ADDRESS"
        chain_config_key: "fee_token_registry_addr"
      Treasury:
        expected_addr_envvar: "EXPECTED_TREASURY_ADDRESS"
        chain_config_key: "treasury_addr"

  actions:
    contracts:
      TransferAction:
        expected_addr_envvar: "EXPECTED_TRANSFER_ACTION_ADDRESS"
        chain_config_key: "actions.transfer"
      TransferERC20Action:
        expected_addr_envvar: "EXPECTED_TRANSFER_ERC20_ACTION_ADDRESS"
        chain_config_key: "actions.transferERC20"
      RefuelAction:
        expected_addr_envvar: "EXPECTED_REFUEL_ACTION_ADDRESS"
        chain_config_key: "actions.refuel"
      RefuelERC20Action:
        expected_addr_envvar: "EXPECTED_REFUEL_ERC20_ACTION_ADDRESS"
        chain_config_key: "actions.refuelERC20"
      DeactivateInstructionAction:
        expected_addr_envvar: "EXPECTED_DEACTIVATE_INSTRUCTION_ACTION_ADDRESS"
        chain_config_key: "actions.deactivateInstruction"
      UniswapV3ExactInputAction:
        chain_config_key: "actions.uniswapV3ExactInput"
      TransferCCTPAction:
        chain_config_key: "actions.transferCCTP"
      SweepCCTPAction:
        chain_config_key: "actions.sweepCCTP"
