contracts:
  - Core
  - FeeTokenRegistry
  - Treasury
  - TransferAction
  - TransferERC20Action
  - RefuelAction
  - RefuelERC20Action
  - UniswapV3ExactInputAction
  - DeactivateInstructionAction
  - SweepAction
  - SweepERC20Action
  - SweepCCTPAction
  - TransferCCTPAction
  - SweepUniswapV3Action

networks:
  - sepolia
  - base-sepolia
  - arbitrum-sepolia
  - optimism-sepolia
