name: Static Analysis

on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: stable
          cache-key: ${{ github.job }}-${{ github.sha }}

      - name: Install Dependencies with Soldeer
        run: forge soldeer update

      - name: Run Slither Analysis
        uses: docker://trailofbits/eth-security-toolbox:latest
        with:
          args: slither /github/workspace --exclude-dependencies --checklist
