name: Run Forge Tests

on:
  push:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    name: Foundry Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: nightly
          cache-key: ${{ github.job }}-${{ github.sha }}

      - name: Build contracts
        run: |
          forge --version
          forge soldeer update
          forge build --sizes

      - name: Check gas snapshot
        run: forge snapshot --check --tolerance 1

      - name: Run tests
        run: forge test -vvv
