name: Test CI Scripts

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/scripts/directory-comparison.rs'
  workflow_dispatch:

jobs:
  test-script:
    name: Test Directory Comparison Script
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # v1
        with:
          toolchain: nightly

      - uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      
      - name: Install rust-script
        run: |
          curl -LsSf https://github.com/fornwall/rust-script/releases/latest/download/rust-script-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
          sudo install rust-script /usr/local/bin/
      
      - name: Run tests
        run: |
          echo "Running tests for directory-comparison.rs"
          cd .github/scripts/
          rust-script --test directory-comparison.rs
